/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MaintenanceListPartDTO } from './maintenance-list-part-dto';
import { MaintenanceServiceDTO } from './maintenance-service-dto';
 /**
 * 
 *
 * @export
 * @interface ApiMaintenanceBody
 */
export interface ApiMaintenanceBody {

    /**
     * @type {string}
     * @memberof ApiMaintenanceBody
     */
    startDate: string;

    /**
     * @type {string}
     * @memberof ApiMaintenanceBody
     */
    finishDate?: string;

    /**
     * @type {string}
     * @memberof ApiMaintenanceBody
     */
    startHour: string;

    /**
     * @type {string}
     * @memberof ApiMaintenanceBody
     */
    finishHour?: string;

    /**
     * @type {string}
     * @memberof ApiMaintenanceBody
     */
    comments?: string;

    /**
     * @type {string}
     * @memberof ApiMaintenanceBody
     */
    reference?: string;

    /**
     * @type {string}
     * @memberof ApiMaintenanceBody
     */
    odometer?: string;

    /**
     * @type {string}
     * @memberof ApiMaintenanceBody
     */
    maintenanceTypeId?: string;

    /**
     * @type {string}
     * @memberof ApiMaintenanceBody
     */
    maintenanceGroupId?: string;

    /**
     * @type {number}
     * @memberof ApiMaintenanceBody
     */
    costLobour?: number;

    /**
     * @type {string}
     * @memberof ApiMaintenanceBody
     */
    providerId?: string;

    /**
     * @type {string}
     * @memberof ApiMaintenanceBody
     */
    vehicleId: string;

    /**
     * @type {Blob}
     * @memberof ApiMaintenanceBody
     */
    documentFile?: Blob;

    /**
     * @type {Array<Blob>}
     * @memberof ApiMaintenanceBody
     */
    imageFiles?: Array<Blob>;

    /**
     * @type {Array<MaintenanceListPartDTO>}
     * @memberof ApiMaintenanceBody
     */
    maintenanceParts?: Array<MaintenanceListPartDTO>;

    /**
     * @type {Array<MaintenanceServiceDTO>}
     * @memberof ApiMaintenanceBody
     */
    maintenanceServices?: Array<MaintenanceServiceDTO>;
}
