/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ApiCompanyBody
 */
export interface ApiCompanyBody {

    /**
     * @type {Blob}
     * @memberof ApiCompanyBody
     */
    logoFile?: Blob;

    /**
     * @type {string}
     * @memberof ApiCompanyBody
     */
    name?: string;

    /**
     * @type {string}
     * @memberof ApiCompanyBody
     */
    description?: string;
}
