/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CatalogsEnum {
    VehicleCategories = 'VehicleCategories',
    FuelTypes = 'FuelTypes',
    Servies = 'Servies',
    Machines = 'Machines',
    Projects = 'Projects',
    MaintenanceGroups = 'MaintenanceGroups',
    Engines = 'Engines',
    Models = 'Models',
    Brands = 'Brands',
    Companies = 'Companies',
    FuelMeasures = 'FuelMeasures',
    Measures = 'Measures',
    ActiveCategories = 'ActiveCategories',
    MaintenanceTypes = 'MaintenanceTypes'
}

