/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TenantCompanyUserPermissionDTO } from './tenant-company-user-permission-dto';
 /**
 * 
 *
 * @export
 * @interface CompanyTenantDTO
 */
export interface CompanyTenantDTO {

    /**
     * @type {string}
     * @memberof CompanyTenantDTO
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof CompanyTenantDTO
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof CompanyTenantDTO
     */
    description?: string | null;

    /**
     * @type {string}
     * @memberof CompanyTenantDTO
     */
    userCreationId?: string | null;

    /**
     * @type {boolean}
     * @memberof CompanyTenantDTO
     */
    owner?: boolean;

    /**
     * @type {Array<TenantCompanyUserPermissionDTO>}
     * @memberof CompanyTenantDTO
     */
    permissions?: Array<TenantCompanyUserPermissionDTO> | null;
}
