/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FuelLoadDTO } from './fuel-load-dto';
;

/**
 * 
 *
 * @export
 * @interface FuelTypeDTO
 */
export interface FuelTypeDTO {

    /**
     * @type {string}
     * @memberof FuelTypeDTO
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof FuelTypeDTO
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof FuelTypeDTO
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof FuelTypeDTO
     */
    description?: string | null;

    /**
     * @type {Array<FuelLoadDTO>}
     * @memberof FuelTypeDTO
     */
    fuelLoads?: Array<FuelLoadDTO> | null;
}
