/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CategoryTypeEnum } from './category-type-enum';
 /**
 * 
 *
 * @export
 * @interface FuelLoadDetailDTO
 */
export interface FuelLoadDetailDTO {

    /**
     * @type {string}
     * @memberof FuelLoadDetailDTO
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof FuelLoadDetailDTO
     */
    ecoNumber?: string | null;

    /**
     * @type {string}
     * @memberof FuelLoadDetailDTO
     */
    chargeDate?: string | null;

    /**
     * @type {string}
     * @memberof FuelLoadDetailDTO
     */
    odometer?: string | null;

    /**
     * @type {string}
     * @memberof FuelLoadDetailDTO
     */
    totalAmount?: string | null;

    /**
     * @type {CategoryTypeEnum}
     * @memberof FuelLoadDetailDTO
     */
    categoryType?: CategoryTypeEnum;
}
