/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PolicyDTO } from './policy-dto';
import { VehicleDTO } from './vehicle-dto';
;

/**
 * 
 *
 * @export
 * @interface IncisoDTO
 */
export interface IncisoDTO {

    /**
     * @type {string}
     * @memberof IncisoDTO
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof IncisoDTO
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof IncisoDTO
     */
    vehicleId?: string | null;

    /**
     * @type {VehicleDTO}
     * @memberof IncisoDTO
     */
    vehicle?: VehicleDTO;

    /**
     * @type {string}
     * @memberof IncisoDTO
     */
    policyId?: string | null;

    /**
     * @type {PolicyDTO}
     * @memberof IncisoDTO
     */
    policy?: PolicyDTO;
}
