/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Policy } from './policy';
;

/**
 * 
 *
 * @export
 * @interface InsuranceCompany
 */
export interface InsuranceCompany {

    /**
     * @type {string}
     * @memberof InsuranceCompany
     */
    id?: string | null;

    /**
     * @type {boolean}
     * @memberof InsuranceCompany
     */
    active?: boolean;

    /**
     * @type {number}
     * @memberof InsuranceCompany
     */
    isActive?: number;

    /**
     * @type {boolean}
     * @memberof InsuranceCompany
     */
    excludeFromLog?: boolean;

    /**
     * @type {string}
     * @memberof InsuranceCompany
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof InsuranceCompany
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof InsuranceCompany
     */
    description?: string | null;

    /**
     * @type {Array<Policy>}
     * @memberof InsuranceCompany
     */
    policies?: Array<Policy> | null;
}
