/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DocumentDTO } from './document-dto';
import { MaintenanceGroupDTO } from './maintenance-group-dto';
import { MaintenancePartDTO } from './maintenance-part-dto';
import { MaintenanceTypeDTO } from './maintenance-type-dto';
import { TimeSpan } from './time-span';
import { VehicleDTO } from './vehicle-dto';
import { VendorDTO } from './vendor-dto';
;

/**
 * 
 *
 * @export
 * @interface MaintenanceDTO
 */
export interface MaintenanceDTO {

    /**
     * @type {string}
     * @memberof MaintenanceDTO
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof MaintenanceDTO
     */
    name?: string | null;

    /**
     * @type {Date}
     * @memberof MaintenanceDTO
     */
    startDate?: Date;

    /**
     * @type {Date}
     * @memberof MaintenanceDTO
     */
    finishDate?: Date | null;

    /**
     * @type {TimeSpan}
     * @memberof MaintenanceDTO
     */
    startHour?: TimeSpan;

    /**
     * @type {TimeSpan}
     * @memberof MaintenanceDTO
     */
    finishHour?: TimeSpan;

    /**
     * @type {string}
     * @memberof MaintenanceDTO
     */
    comments?: string | null;

    /**
     * @type {string}
     * @memberof MaintenanceDTO
     */
    odometer?: string | null;

    /**
     * @type {string}
     * @memberof MaintenanceDTO
     */
    maintenanceTypeId?: string | null;

    /**
     * @type {string}
     * @memberof MaintenanceDTO
     */
    maintenanceGroupId?: string | null;

    /**
     * @type {string}
     * @memberof MaintenanceDTO
     */
    vendorId?: string | null;

    /**
     * @type {string}
     * @memberof MaintenanceDTO
     */
    vehicleId?: string | null;

    /**
     * @type {string}
     * @memberof MaintenanceDTO
     */
    documentId?: string | null;

    /**
     * @type {VendorDTO}
     * @memberof MaintenanceDTO
     */
    vendor?: VendorDTO;

    /**
     * @type {DocumentDTO}
     * @memberof MaintenanceDTO
     */
    document?: DocumentDTO;

    /**
     * @type {MaintenanceGroupDTO}
     * @memberof MaintenanceDTO
     */
    maintenanceGroup?: MaintenanceGroupDTO;

    /**
     * @type {MaintenanceTypeDTO}
     * @memberof MaintenanceDTO
     */
    maintenanceType?: MaintenanceTypeDTO;

    /**
     * @type {VehicleDTO}
     * @memberof MaintenanceDTO
     */
    vehicle?: VehicleDTO;

    /**
     * @type {Array<MaintenancePartDTO>}
     * @memberof MaintenanceDTO
     */
    maintenanceParts?: Array<MaintenancePartDTO> | null;
}
