/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PermissionsEnum } from './permissions-enum';
 /**
 * 
 *
 * @export
 * @interface PermissionFormDTO
 */
export interface PermissionFormDTO {

    /**
     * @type {PermissionsEnum}
     * @memberof PermissionFormDTO
     */
    permission?: PermissionsEnum;

    /**
     * @type {boolean}
     * @memberof PermissionFormDTO
     */
    had?: boolean;

    /**
     * @type {string}
     * @memberof PermissionFormDTO
     */
    description?: string | null;
}
