/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PolicyDTO } from './policy-dto';
;

/**
 * 
 *
 * @export
 * @interface PolicyStatusDTO
 */
export interface PolicyStatusDTO {

    /**
     * @type {string}
     * @memberof PolicyStatusDTO
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof PolicyStatusDTO
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof PolicyStatusDTO
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof PolicyStatusDTO
     */
    description?: string | null;

    /**
     * @type {Array<PolicyDTO>}
     * @memberof PolicyStatusDTO
     */
    policies?: Array<PolicyDTO> | null;
}
