/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InsuranceCompany } from './insurance-company';
import { PolicyPacket } from './policy-packet';
import { PolicyStatus } from './policy-status';
import { Vehicle } from './vehicle';
;

/**
 * 
 *
 * @export
 * @interface Policy
 */
export interface Policy {

    /**
     * @type {string}
     * @memberof Policy
     */
    id?: string | null;

    /**
     * @type {boolean}
     * @memberof Policy
     */
    active?: boolean;

    /**
     * @type {number}
     * @memberof Policy
     */
    isActive?: number;

    /**
     * @type {boolean}
     * @memberof Policy
     */
    excludeFromLog?: boolean;

    /**
     * @type {string}
     * @memberof Policy
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof Policy
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof Policy
     */
    description?: string | null;

    /**
     * @type {Date}
     * @memberof Policy
     */
    startDate?: Date;

    /**
     * @type {Date}
     * @memberof Policy
     */
    endDate?: Date;

    /**
     * @type {number}
     * @memberof Policy
     */
    quantityVehicles?: number;

    /**
     * @type {Array<Vehicle>}
     * @memberof Policy
     */
    vehicles?: Array<Vehicle> | null;

    /**
     * @type {string}
     * @memberof Policy
     */
    policyStatusId?: string | null;

    /**
     * @type {PolicyStatus}
     * @memberof Policy
     */
    policyStatus?: PolicyStatus;

    /**
     * @type {string}
     * @memberof Policy
     */
    policyPacketId?: string | null;

    /**
     * @type {PolicyPacket}
     * @memberof Policy
     */
    policyPacket?: PolicyPacket;

    /**
     * @type {string}
     * @memberof Policy
     */
    insuranceCompanyId?: string | null;

    /**
     * @type {InsuranceCompany}
     * @memberof Policy
     */
    insuranceCompany?: InsuranceCompany;
}
