/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InsuranceCompanyDTO } from './insurance-company-dto';
import { PolicyPacketDTO } from './policy-packet-dto';
import { PolicyStatusDTO } from './policy-status-dto';
import { VehicleDTO } from './vehicle-dto';
;

/**
 * 
 *
 * @export
 * @interface PolicyDTO
 */
export interface PolicyDTO {

    /**
     * @type {string}
     * @memberof PolicyDTO
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof PolicyDTO
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof PolicyDTO
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof PolicyDTO
     */
    description?: string | null;

    /**
     * @type {Date}
     * @memberof PolicyDTO
     */
    startDate?: Date;

    /**
     * @type {Date}
     * @memberof PolicyDTO
     */
    endDate?: Date;

    /**
     * @type {number}
     * @memberof PolicyDTO
     */
    quantityVehicles?: number;

    /**
     * @type {Array<VehicleDTO>}
     * @memberof PolicyDTO
     */
    vehicles?: Array<VehicleDTO> | null;

    /**
     * @type {string}
     * @memberof PolicyDTO
     */
    policyStatusId?: string | null;

    /**
     * @type {PolicyStatusDTO}
     * @memberof PolicyDTO
     */
    policyStatus?: PolicyStatusDTO;

    /**
     * @type {string}
     * @memberof PolicyDTO
     */
    policyPacketId?: string | null;

    /**
     * @type {PolicyPacketDTO}
     * @memberof PolicyDTO
     */
    policyPacket?: PolicyPacketDTO;

    /**
     * @type {string}
     * @memberof PolicyDTO
     */
    insuranceCompanyId?: string | null;

    /**
     * @type {InsuranceCompanyDTO}
     * @memberof PolicyDTO
     */
    insuranceCompany?: InsuranceCompanyDTO;
}
