/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {

    /**
     * @type {string}
     * @memberof ProblemDetails
     */
    detail?: string | null;

    /**
     * @type {string}
     * @memberof ProblemDetails
     */
    instance?: string | null;

    /**
     * @type {any}
     * @memberof ProblemDetails
     */
    additionalProperties?: any;

    /**
     * @type {string}
     * @memberof ProblemDetails
     */
    type?: string | null;

    /**
     * @type {string}
     * @memberof ProblemDetails
     */
    title?: string | null;

    /**
     * @type {number}
     * @memberof ProblemDetails
     */
    status?: number | null;
}
