/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DocumentDTO } from './document-dto';
import { MaintenanceDTO } from './maintenance-dto';
import { PolicyDTO } from './policy-dto';
;

/**
 * 
 *
 * @export
 * @interface ProjectDTO
 */
export interface ProjectDTO {

    /**
     * @type {string}
     * @memberof ProjectDTO
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof ProjectDTO
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof ProjectDTO
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof ProjectDTO
     */
    description?: string | null;

    /**
     * @type {number}
     * @memberof ProjectDTO
     */
    externalId?: number;

    /**
     * @type {string}
     * @memberof ProjectDTO
     */
    packetId?: string | null;

    /**
     * @type {PolicyDTO}
     * @memberof ProjectDTO
     */
    packet?: PolicyDTO;

    /**
     * @type {string}
     * @memberof ProjectDTO
     */
    documentId?: string | null;

    /**
     * @type {DocumentDTO}
     * @memberof ProjectDTO
     */
    document?: DocumentDTO;

    /**
     * @type {string}
     * @memberof ProjectDTO
     */
    maintenanceId?: string | null;

    /**
     * @type {MaintenanceDTO}
     * @memberof ProjectDTO
     */
    maintenance?: MaintenanceDTO;
}
