/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

;

/**
 * 
 *
 * @export
 * @interface ResetPasswordModel
 */
export interface ResetPasswordModel {

    /**
     * @type {string}
     * @memberof ResetPasswordModel
     */
    password: string;

    /**
     * @type {string}
     * @memberof ResetPasswordModel
     */
    confirmPassword: string;

    /**
     * @type {string}
     * @memberof ResetPasswordModel
     */
    email: string;

    /**
     * @type {string}
     * @memberof ResetPasswordModel
     */
    token: string;
}
