/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TenantLinkUserDTO
 */
export interface TenantLinkUserDTO {

    /**
     * @type {string}
     * @memberof TenantLinkUserDTO
     */
    tenantCompanyId?: string | null;

    /**
     * @type {string}
     * @memberof TenantLinkUserDTO
     */
    tenantCompanyName?: string | null;

    /**
     * @type {string}
     * @memberof TenantLinkUserDTO
     */
    userEmail?: string | null;
}
