/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AppUsuario } from './app-usuario';
import { TenantCompany } from './tenant-company';
import { TenantLinkStatusEnum } from './tenant-link-status-enum';
 /**
 * 
 *
 * @export
 * @interface TenantLink
 */
export interface TenantLink {

    /**
     * @type {number}
     * @memberof TenantLink
     */
    id?: number;

    /**
     * @type {string}
     * @memberof TenantLink
     */
    tenantCompanyId?: string | null;

    /**
     * @type {string}
     * @memberof TenantLink
     */
    userId?: string | null;

    /**
     * @type {TenantLinkStatusEnum}
     * @memberof TenantLink
     */
    status?: TenantLinkStatusEnum;

    /**
     * @type {TenantCompany}
     * @memberof TenantLink
     */
    tenantCompany?: TenantCompany;

    /**
     * @type {AppUsuario}
     * @memberof TenantLink
     */
    user?: AppUsuario;
}
