/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GenderEnum } from './gender-enum';
import { RoleTenantDTO } from './role-tenant-dto';
 /**
 * 
 *
 * @export
 * @interface UserCreateUserBody
 */
export interface UserCreateUserBody {

    /**
     * @type {string}
     * @memberof UserCreateUserBody
     */
    email: string;

    /**
     * @type {string}
     * @memberof UserCreateUserBody
     */
    password: string;

    /**
     * @type {Blob}
     * @memberof UserCreateUserBody
     */
    imageFile?: Blob;

    /**
     * @type {string}
     * @memberof UserCreateUserBody
     */
    firstName: string;

    /**
     * @type {string}
     * @memberof UserCreateUserBody
     */
    lastName: string;

    /**
     * @type {GenderEnum}
     * @memberof UserCreateUserBody
     */
    gender?: GenderEnum;

    /**
     * @type {string}
     * @memberof UserCreateUserBody
     */
    phoneNumber: string;

    /**
     * @type {Array<RoleTenantDTO>}
     * @memberof UserCreateUserBody
     */
    roleCompany?: Array<RoleTenantDTO>;
}
