/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AppUsuario } from './app-usuario';
import { Role } from './role';
;

/**
 * 
 *
 * @export
 * @interface UserRole
 */
export interface UserRole {

    /**
     * @type {string}
     * @memberof UserRole
     */
    userId?: string | null;

    /**
     * @type {string}
     * @memberof UserRole
     */
    roleId?: string | null;

    /**
     * @type {AppUsuario}
     * @memberof UserRole
     */
    user?: AppUsuario;

    /**
     * @type {Role}
     * @memberof UserRole
     */
    role?: Role;
}
