/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface VehicleInboxDTO
 */
export interface VehicleInboxDTO {

    /**
     * @type {string}
     * @memberof VehicleInboxDTO
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof VehicleInboxDTO
     */
    description?: string | null;

    /**
     * @type {string}
     * @memberof VehicleInboxDTO
     */
    assignedTo?: string | null;

    /**
     * @type {string}
     * @memberof VehicleInboxDTO
     */
    economicNumber?: string | null;

    /**
     * @type {string}
     * @memberof VehicleInboxDTO
     */
    vin?: string | null;

    /**
     * @type {string}
     * @memberof VehicleInboxDTO
     */
    placas?: string | null;

    /**
     * @type {string}
     * @memberof VehicleInboxDTO
     */
    category?: string | null;

    /**
     * @type {string}
     * @memberof VehicleInboxDTO
     */
    projectName?: string | null;

    /**
     * @type {string}
     * @memberof VehicleInboxDTO
     */
    machineId?: string | null;

    /**
     * @type {string}
     * @memberof VehicleInboxDTO
     */
    companyId?: string | null;
}
