/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface VehicleFormDTO
 */
export interface VehicleFormDTO {

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    description: string;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    assignedId?: string | null;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    brandId?: string | null;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    modelId?: string | null;

    /**
     * @type {number}
     * @memberof VehicleFormDTO
     */
    modelYear?: number;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    engineId?: string | null;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    placas?: string | null;

    /**
     * @type {number}
     * @memberof VehicleFormDTO
     */
    drillRigId?: number;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    policyId?: string | null;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    incisoId?: string | null;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    packagePolicyId?: string | null;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    measureId?: string | null;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    fuelMeasureId?: string | null;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    fuelTypeId?: string | null;

    /**
     * @type {number}
     * @memberof VehicleFormDTO
     */
    tankSize?: number;

    /**
     * @type {boolean}
     * @memberof VehicleFormDTO
     */
    active?: boolean;

    /**
     * @type {Array<Blob>}
     * @memberof VehicleFormDTO
     */
    photographsFiles?: Array<Blob> | null;

    /**
     * @type {Blob}
     * @memberof VehicleFormDTO
     */
    billFile?: Blob | null;

    /**
     * @type {Blob}
     * @memberof VehicleFormDTO
     */
    pedimentoFile?: Blob | null;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    vin?: string | null;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    machineId?: string | null;

    /**
     * @type {string}
     * @memberof VehicleFormDTO
     */
    economicNumber?: string | null;
}
