/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Document } from './document';
import { FuelLoad } from './fuel-load';
import { Model } from './model';
import { Policy } from './policy';
import { VehicleType } from './vehicle-type';
;

/**
 * 
 *
 * @export
 * @interface Vehicle
 */
export interface Vehicle {

    /**
     * @type {string}
     * @memberof Vehicle
     */
    id?: string | null;

    /**
     * @type {boolean}
     * @memberof Vehicle
     */
    active?: boolean;

    /**
     * @type {number}
     * @memberof Vehicle
     */
    isActive?: number;

    /**
     * @type {boolean}
     * @memberof Vehicle
     */
    excludeFromLog?: boolean;

    /**
     * @type {number}
     * @memberof Vehicle
     */
    drillRigId?: number;

    /**
     * @type {string}
     * @memberof Vehicle
     */
    vin?: string | null;

    /**
     * @type {string}
     * @memberof Vehicle
     */
    placas?: string | null;

    /**
     * @type {string}
     * @memberof Vehicle
     */
    inciso?: string | null;

    /**
     * @type {string}
     * @memberof Vehicle
     */
    economicNumber?: string | null;

    /**
     * @type {string}
     * @memberof Vehicle
     */
    modelId?: string | null;

    /**
     * @type {Model}
     * @memberof Vehicle
     */
    model?: Model;

    /**
     * @type {string}
     * @memberof Vehicle
     */
    documentId?: string | null;

    /**
     * @type {Document}
     * @memberof Vehicle
     */
    document?: Document;

    /**
     * @type {string}
     * @memberof Vehicle
     */
    policyId?: string | null;

    /**
     * @type {Policy}
     * @memberof Vehicle
     */
    policy?: Policy;

    /**
     * @type {string}
     * @memberof Vehicle
     */
    vehicleTypeId?: string | null;

    /**
     * @type {VehicleType}
     * @memberof Vehicle
     */
    vehicleType?: VehicleType;

    /**
     * @type {Array<FuelLoad>}
     * @memberof Vehicle
     */
    fuelLoads?: Array<FuelLoad> | null;
}
