/* tslint:disable */
/* eslint-disable */
/**
 * PROJECT API - Development
 * PROJECT .NET Core Web API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface VendorDTO
 */
export interface VendorDTO {

    /**
     * @type {string}
     * @memberof VendorDTO
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof VendorDTO
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof VendorDTO
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof VendorDTO
     */
    description?: string | null;
}
